[versions]
minecraft = "1.21.1"

# Loaders
neoforge_version = "21.1.215"

aj4j = "1.7.9"
ak4j = "1.0.1"
cookielib = "1.2.1"
kff = "5.5.50"

[libraries]
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge_version" }
aj4j = { group = "club.snowlyicewolf", name = "amarok-json-for-java", version.ref = "aj4j" }
ak4j = { group = "club.snowlyicewolf", name = "amarok-kdl-for-java", version.ref = "ak4j" }
cookielib = { group = "club.someoneice.cookie", name = "PineappleCookie", version.ref = "cookielib" }

